// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYfpln7bKzzic76T9t2YORklTs_2dN2G0',
    appId: '1:664966119047:web:c1e2337e8b92fcbd508222',
    messagingSenderId: '664966119047',
    projectId: 'social-app-2b802',
    authDomain: 'social-app-2b802.firebaseapp.com',
    storageBucket: 'social-app-2b802.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8lsiV38eADUp-gOR8s9IrLcTSPYDPNc',
    appId: '1:664966119047:android:e2f521bbd1bec4a0508222',
    messagingSenderId: '664966119047',
    projectId: 'social-app-2b802',
    storageBucket: 'social-app-2b802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwMWrIQXYzkA1FmWTgPTRwBcq1h0fh0wM',
    appId: '1:664966119047:ios:9d737c6071580925508222',
    messagingSenderId: '664966119047',
    projectId: 'social-app-2b802',
    storageBucket: 'social-app-2b802.appspot.com',
    iosBundleId: 'com.example.social',
  );
}
